name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.6.0 ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test:ci
      - name: Jest Reporter
        uses: tanmen/jest-reporter@v1.5
        if: always()
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            result-file: .\simplecrmweb-no-cra\result.json